---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
  - package-ecosystem: terraform
    directory: modules/aws-asg
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
  - package-ecosystem: terraform
    directory: modules/aws-asg/examples
    open-pull-requests-limit: 5
    schedule:
      interval: monthly
      day: wednesday
