name: Terraform Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

defaults:
  run:
    shell: sh

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: find ./modules/ -maxdepth 1 -mindepth 1
          -exec terraform init {} \;
          -exec terraform validate {} \;

  format:
    name: Format
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: terraform fmt -check -diff -recursive

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: terraform-linters/setup-tflint@v1.1.0
      - name: Show version
        run: tflint --version
      - name: Run
        run: >
          find ./modules/ -maxdepth 1 -mindepth 1
          -exec tflint {} --loglevel=info \;

  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      security-events: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
