name: Terraform Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: sh

jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: find ./modules/ -maxdepth 1 -mindepth 1
          -exec terraform init {} \;
          -exec terraform validate {} \;

  format:
    name: Format
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: terraform fmt -check -diff -recursive

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: wata727/tflint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: >
          find ./modules/ -maxdepth 1 -mindepth 1
          -exec tflint {} --loglevel=info \;

  security:
    name: Security
    runs-on: ubuntu-latest
    container:
      image: liamg/tfsec
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Security
        run: /usr/bin/tfsec ./modules --verbose
