name: Terraform Security

on:
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      security-events: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: tfsec.sarif
